version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    restart: always
